@baseurl = http://localhost:3000

@calendar = http://localhost:3000/calendar
@calendarId = 696e23d3518f951439fa4adb

@people = http://localhost:3000/people
@peopleID = 696e1b7e518f951439fa4ad6

### test local deployment
GET {{baseurl}}

### get all calendar events
GET {{calendar}}

### get calendar event by id
GET {{calendar}}/{{calendarId}}

### get all people
GET {{people}}
### get people by id
GET {{people}}/{{peopleID}} 

### create a new people
POST {{people}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "New",
    "lastName": "People",
    "displayName": "Newbie",
    "role": "other",
    "displayColor": "#fff533"
}

### update a people
PUT {{people}}/{{peopleID}} HTTP/1.1
Content-Type: application/json

{
    "firstName": "Elliott",
    "lastName": "Tompkins",
    "displayName": "Elliott",
    "role": "child",
    "displayColor": "#be33ff"
}

### delete a people
DELETE {{people}}/{{peopleID}} HTTP/1.1   

### create a new calendar event
POST {{calendar}} HTTP/1.1
Content-Type: application/json

{   
    "eventTitle": "New Event1",
    "eventDate": "2026-02-01",
    "startTime": "19:00",
    "endTime": "20:00",
    "eventDescription": "Dinner at Grandma's house",
    "eventLocation": "123 Main St, Hometown, USA",
    "person": "Tompkins Family  "
}

### update a calendar event
PUT {{calendar}}/{{calendarId}} HTTP/1.1
Content-Type: application/json

{   "eventTitle": "Updated Event2",
    "eventDate": "2026-02-02",
    "startTime": "19:00",
    "endTime": "21:00",
    "eventDescription": "Therapy session",
    "eventLocation": "456 Oak St, Hometown, USA",
    "person": "Elliott"
}   

### delete a calendar event
DELETE {{calendar}}/696e29e19f43ea9712175965 HTTP/1.1 